---
title: "JSC370 Final Project"
author: "Yunni Qu"
output: 
    html_document:
        toc: TRUE
        toc_float: TRUE
---

This is my JSC370 Final Project website.
```{r setup, echo=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  warning = FALSE,
  cache = TRUE
)
library(dplyr)
library(plotly)
source("process_COVID_data.R")
```


```{r create_plots}
p1_scatter <- cv_states_today %>% 
  plot_ly(x = ~pop_density, y = ~deathsper100k,
          type = 'scatter', mode = 'markers', color = ~state,
          size = ~population, sizes = c(5, 70), marker = list(sizemode='diameter', opacity=0.5),
          hoverinfo = 'text',
          text = ~paste( paste(state, ":", sep=""), paste(" Cases per 100k: ", per100k, sep="") , paste(" Deaths per 100k: ",
                        deathsper100k, sep=""), sep = "<br>")) %>%
  layout(title = "Population-normalized COVID-19 deaths vs. population density",
                  yaxis = list(title = "Deaths per 100k"), xaxis = list(title = "Population Density"),
         hovermode = "compare")

# filter out "District of Columbia"
cv_states_today_scatter <- cv_states_today %>% filter(state!="District of Columbia")

p2_scatter <- 
  plot_ly(x = ~pop_density, y = ~deathsper100k,
          type = 'scatter', mode = 'markers', color = ~state,
          size = ~population, sizes = c(5, 70), marker = list(sizemode='diameter', opacity=0.5),
          hoverinfo = 'text',
          text = ~paste( paste(state, ":", sep=""), paste(" Cases per 100k: ", per100k, sep="") , paste(" Deaths per 100k: ",
                        deathsper100k, sep=""), sep = "<br>")) %>%
  layout(title = "Population-normalized COVID-19 deaths vs. population density",
                  yaxis = list(title = "Deaths per 100k"), xaxis = list(title = "Population Density"),
         hovermode = "compare")

scatter_p1 <- cv_states_today %>% filter(state!='District of Columbia') %>% plot_ly( x = ~pop_density, y = ~deathsper100k, color = ~state, colors = "Set1",
             size = ~population, type = "scatter", mode = "markers",
             hoverinfo = "text",
             text = ~paste(state, "<br>"))


p2 = plot_ly(
  cv_states_today,
  x = ~ log(pop_density),
  y = ~ per100k,
  color = ~ state,
  size = ~ deathsper100k,
  type = "scatter",
  sizes = c(5, 500),
  marker = list(sizemode = "area", opacity = .8),
  hoverinfo = "text",
  text = ~ paste0(
    state, "\n",
    "  Cases per 100k: ", per100k, "\n",
    "  Deaths per 100k: ", deathsper100k, "\n",
    "  Population density: ", round(pop_density, 1), 
    " per sq miles"
  )
) |>
  layout(hovermode = "x") # compares states with similair x values on hover
```

## Showing plots {.tabset}

### Figure 1
```{r}
scatter_p1
```


### Figure 2
```{r}
p2
```

